name: diary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0  # Latest stable version
  firebase_auth: ^5.6.0   # Latest stable version
  firebase_analytics: ^11.5.0  # Latest stable version
  flutter_bloc: ^9.1.1     # Latest stable version
  #firebase_core_web: ^2.24.0  # Latest stable version
  cloud_firestore: ^5.6.9  # Latest stable version
  intl: ^0.20.2            # Latest stable version
  lottie: ^3.1.3          # Latest stable version
  flutter_launcher_icons: ^0.14.4  # Latest stable version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0    # Keep as is or update to ^6.0.0 if desired

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/