// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByx6Gs_UUckbaifEPrVYRJRXOAhhhFCWw',
    appId: '1:409501972670:web:62ced232c18d92b5dd46ef',
    messagingSenderId: '409501972670',
    projectId: 'diary-21900',
    authDomain: 'diary-21900.firebaseapp.com',
    storageBucket: 'diary-21900.firebasestorage.app',
    measurementId: 'G-RT24T3Z1L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZc-psY1k6cuIqyL-VUVswIDh_9kbNyU',
    appId: '1:409501972670:android:89c173a7bfd298f1dd46ef',
    messagingSenderId: '409501972670',
    projectId: 'diary-21900',
    storageBucket: 'diary-21900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_6-M7OTXh7d_DKDnHSiNAlQKWTwreig',
    appId: '1:409501972670:ios:ab08ba0b24016959dd46ef',
    messagingSenderId: '409501972670',
    projectId: 'diary-21900',
    storageBucket: 'diary-21900.firebasestorage.app',
    iosBundleId: 'com.example.diary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_6-M7OTXh7d_DKDnHSiNAlQKWTwreig',
    appId: '1:409501972670:ios:ab08ba0b24016959dd46ef',
    messagingSenderId: '409501972670',
    projectId: 'diary-21900',
    storageBucket: 'diary-21900.firebasestorage.app',
    iosBundleId: 'com.example.diary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByx6Gs_UUckbaifEPrVYRJRXOAhhhFCWw',
    appId: '1:409501972670:web:c010f47309c7ab82dd46ef',
    messagingSenderId: '409501972670',
    projectId: 'diary-21900',
    authDomain: 'diary-21900.firebaseapp.com',
    storageBucket: 'diary-21900.firebasestorage.app',
    measurementId: 'G-2341LS0RG0',
  );
}
