import 'package:diary/Splash_screen/darksplash.dart';
import 'package:diary/screen/homepage.dart';
import 'package:diary/Auth_screen/login.dart';
import 'package:diary/Splash_screen/splash_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // ✅ Generated by `flutterfire configure`

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FlutterError.onError = (FlutterErrorDetails details) {
    // Only in debug/release error logging
    FlutterError.dumpErrorToConsole(details);
    // Optionally send to analytics/crashlytics
  };

  runApp(const MyApp());
}


class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late bool _isNightMode;

  @override
  void initState() {
    super.initState();
    final hour = DateTime.now().hour;
    _isNightMode = hour < 6 || hour >= 18;
  }

  void _updateTheme() {
    final hour = DateTime.now().hour;
    setState(() {
      _isNightMode = hour < 6 || hour >= 18;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'My Diary',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: _isNightMode ? splash() : SplashScreen(),
    );
  }
}
